# Configuration du serveur
server:
  port: 8083

spring:
  application:
    name: payment-service
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5435/esales_payments
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuration des microservices
order:
  service:
    url: http://localhost:8082

user:
  service:
    url: http://localhost:8081

# Configuration des délais de paiement (en heures)
payment:
  expiration:
    delay: 24
  methods: CARTE_BANCAIRE,PAYPAL,VIREMENT

logging:
  level:
    org:
      springframework:
        web: DEBUG